TW-4 레이아웃 수정
Co-Run-Toy-Project/tway-develop-project pull request #7
Opened 2022-10-09 14:29 UTC by Inside-eun

![image](https://user-images.githubusercontent.com/103915161/194762411-636a22fd-5e33-4779-8cb5-68fc0a70c3be.png)
파일 날라가서 이성 잃을뻔 했으나 침착하게 복구...
캐러셀은 다른 화면으로 테스트 해보다 내일 중으로 올려보겠습니다.

2022-10-09 18:23 UTC, dorrion requested changes
담은님 ! master 브랜치로 merge 요청하고 있어요! develop으로 바꿔주셔야 할 것 같습니당!

2022-10-10 10:19 UTC, yeowool1010 approved these changes

2022-10-10 14:51 UTC, hun0613 approved these changes

2022-10-11 08:47 UTC, dorrion approved these changes
고생하셨어요!

2022-10-11 10:55 UTC, rachelyu1025 approved these changes

2022-10-11 11:05 UTC, merged